### ISSUE TITLE
Triage report doesn't show completely correct

### ISSUE THREAD

**Issue by beamzer** [InQuest/python-sandboxapi#15]
Hi, I made a dedicated uploader for triage, which works:
https://ghostbin.co/paste/45zt4

But the parsing of the return data fails in the end, any idea what goes wrong?
```% python3 triage.py ../malware/september-16-919948-2020.doc 
file ../malware/september-16-919948-2020.doc submitted for analysis, id 200916-2tvp3z18mn
not done yet, sleeping 10 seconds...
...etc
not done yet, sleeping 10 seconds...
analysis complete. fetching report...
{'completed': '2020-09-16T18:19:16Z',
 'created': '2020-09-16T18:16:41Z',
 'custom': 'frontend:269e478c-8ea9-49af-bfad-ce25b55713b9',
 'owner': 'shark2.ams5.hatching.io',
 'sample': '200916-2tvp3z18mn',
 'score': 10,
 'sha256': '44d6c7f1c3536454a19ef188240a6f58c415fb2da863308610e7e27a66e562cb',
 'status': 'reported',
 'target': '../malware/september-16-919948-2020.doc',
 'tasks': {'200916-2tvp3z18mn-behavioral1': {'backend': 'horse2',
                                             'kind': 'behavioral',
                                             'platform': 'windows7_x64',
                                             'queue_id': 1910667,
                                             'resource': 'win7v200722',
                                             'score': 10,
                                             'status': 'reported',
                                             'tags': ['trojan',
                                                      'banker',
                                                      'family:emotet'],
                                             'target': '../malware/september-16-919948-2020.doc'},
           '200916-2tvp3z18mn-behavioral2': {'backend': 'fu1m1',
                                             'kind': 'behavioral',
                                             'platform': 'windows10_x64',
                                             'queue_id': 1910668,
                                             'resource': 'win10',
                                             'score': 10,
                                             'status': 'reported',
                                             'tags': ['trojan',
                                                      'banker',
                                                      'family:emotet'],
                                             'target': '../malware/september-16-919948-2020.doc'},
           '200916-2tvp3z18mn-static1': {'kind': 'static',
                                         'score': 8,
                                         'status': 'reported',
                                         'tags': ['macro']}}}
Traceback (most recent call last):
  File "triage.py", line 31, in <module>
    print("Score: {score}".format(score=sandbox.score(report)))
  File "/home/remnux/.local/lib/python3.6/site-packages/sandboxapi/triage.py", line 148, in score
    report = self.report(item_id)
  File "/home/remnux/.local/lib/python3.6/site-packages/sandboxapi/triage.py", line 136, in report
    data = self.request("/samples/{:s}/summary".format(item_id))
TypeError: unsupported format string passed to dict.__format__
```

**Comment by cmmorrow** [comment]
Hi @beamzer,

The issue you are seeing is because the `score()` method is expecting the analysis ID as an argument but you are passing the report as an argument. If you change the last line of your application to `print("Score: {score}".format(score=sandbox.score(file_id)))`, I think it will work.

BTW, this is inconsistent with how the API works for other sandboxes. For the rest of the sandboxes, the `score()` method accepts the report dictionary (as your application currently does). I'll submit a PR to change `score()` to accept the report as an argument instead of the file ID.

In the meantime, the change mentioned above should hopefully work.

**Comment by beamzer** [comment]
Great, that fixed it.
thanks for helping me out,

Ewald...
